version: "3.9"
services:
    api:
        build: .
        container_name: time_tracker_api
        command: ["./docker/app.sh"]
        ports:
          - '80:80'
        volumes:
          - ".:/TimeTracker"
        depends_on:
          - postgres-db

    postgres-db:
        container_name: postgres_db_container
        image: postgres:16.1-alpine
        environment:
            POSTGRES_DB: ${PG_DB_NAME}
            POSTGRES_USER: ${PG_DB_USER}
            POSTGRES_PASSWORD: ${PG_DB_PASSWORD}
        ports:
          - ${PG_DB_PORT}:5432
        env_file:
          - tests/.env-tests
