version: "3.9"
services:
    api:
        build: .
        container_name: time_tracker_api
        command: ["./docker/app.sh"]
        ports:
          - '80:80'
        volumes:
          - ".:/backend"
        depends_on:
          - postgres-db
        env_file:
          - .env

    postgres-db:
        container_name: postgres_db_container
        image: postgres:16.1-alpine
        environment:
            POSTGRES_DB: ${PG_DB_NAME}
            POSTGRES_USER: ${PG_DB_USER}
            POSTGRES_PASSWORD: ${PG_DB_PASSWORD}
        ports:
          - ${PG_DB_PORT}:5432
        volumes:
          - ./postgres/init:/docker-entrypoint-initdb.d
          - ./postgres:/var/lib/postgres/data

#    pgadmin:
#        container_name: pgadmin_container
#        image: dpage/pgadmin4:7.2
#        environment:
#            PGADMIN_DEFAULT_EMAIL: "email@email.com"
#            PGADMIN_DEFAULT_PASSWORD: "qwerty"
#            PGADMIN_CONFIG_SERVER_MODE: "False"
#        ports:
#          - "5050:80"
