name: checks

on:
    push:
    pull_request:
        branches: [ "main" ]

permissions:
  contents: read

jobs:
    style:
        name: check code style
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v4
          - uses: pre-commit/action@v3.0.1

    build:
        name: tests
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - name: Set up Python 3.12
            uses: actions/setup-python@v4
            with:
               python-version: "3.12"

          - name: run_tests
            run: |
                docker-compose --env-file tests/.env-tests -f docker-compose-test.yml up -d --build
                docker-compose --env-file tests/.env-tests -f docker-compose-test.yml exec -T api pytest -vv
                docker-compose --env-file tests/.env-tests -f docker-compose-test.yml down -v
