name: CI

on:
    pull_request:

jobs:
    run_tests:
        strategy:
            fail-fast: false
            matrix:
                os: ubuntu-latest

        name: Tests
        runs-on: ${{ matrix.os }}
        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: run tests
              run: |
                    docker-compose -f docker-compose-test.yml up -d --build
                    docker-compose -f docker-compose-test.yml exec -T api pytest -vv
                    docker-compose -f docker-compose-test.yml down -v
