name: Tests

on:
    push:
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

permissions:
  contents: read

jobs:
    build:
        name: tests
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3

          - name: Set up Python 3.12
            uses: actions/setup-python@v3
            with:
               python-version: "3.12"

          -   name: Install poetry
              run: |
                  python -m pip install --no-cache-dir poetry==1.7.1
                  poetry config virtualenvs.create false

          - name: run_tests
            run: |
                docker-compose --env-file tests/.env-tests -f docker-compose-test.yml up -d --build
                docker-compose --env-file tests/.env-tests -f docker-compose-test.yml exec -T api pytest -vv
                docker-compose -f docker-compose-test.yml down -v
